### PR TITLE
Update to Node 18

### PR DESCRIPTION
**Pull request by nc-abunimehw**

### CODE REVIEW

**Comment by nc-chowa** [comment]
were you able to run this locally and hit the localhost endpoint without the need for setting this? `NODE_OPTIONS=--dns-result-order=ipv4first`

**Review by nc-kreiserm — COMMENTED** [review]
lgtm. will approve:
- it's tuesday
- dependencies are merged and installed
- proof of life (screenshots are good)

**Review by NC-piercej — COMMENTED** [review]
Seems fine to me.

**Review by nc-chowa — APPROVED** [review]

**Review by NC-piercej — APPROVED** [review]
🚀

**Pull request merged**
